spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CN
    username: root
    password: lalorsh6471!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
